version: '3.9'

services:
  lint-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-utils-ci:latest
    command: ["make", "lint-check"]
    environment:
      - ENV=test

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-utils-ci:latest
    command: ["make", "test"]
    environment:
      - CHAIN=GOERLI
      - WEB3_PROVIDER_URL
