name: Huma Utils CI for Merging to Develop

on:
  push:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: docker-compose -f ./docker-compose-ci.yml run lint-tests

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit and e2e tests
        env:
          WEB3_PROVIDER_URL: ${{ secrets.WEB3_PROVIDER_URL }}
        run: docker-compose -f ./docker-compose-ci.yml run tests
