name: gitleaks

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: ["main", "develop"]

  workflow_dispatch:

jobs:
  check-secret-leakage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - uses: gitleaks/gitleaks-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
